spring:
  application:
    name: viet-phuc-store
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        connection:
          characterEncoding: UTF-8
          useUnicode: true
          charSet: UTF-8
        jdbc:
          batch_size: 25
        order_updates: true
        order_inserts: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      connection-init-sql: "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci"
      data-source-properties:
        useSSL: false
        characterEncoding: UTF-8
        useUnicode: true
        serverTimezone: Asia/Ho_Chi_Minh
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        ssl:
          trust: smtp.gmail.com
server:
  port: 8082
  servlet:
    context-path: /nextrad/api
#  ssl:
#    key-store-type: ${SSL_KEY_STORE_TYPE}
#    key-store: ${SSL_KEY_STORE_PATH}
#    key-alias: ${SSL_KEY_ALIAS}
#    key-store-password: ${SSL_KEY_STORE_PASSWORD}
#    enabled: true